# Generated by Django 3.2.11 on 2022-02-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
